version: "3.8"

services:
  api:
    build: ./api
    container_name: carmeet_api
    restart: always
    env_file:
      - ./api/.env
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      DB_HOST: db
    networks:
      - carmeet-net

  front:
    build: ./front
    container_name: carmeet_front
    restart: always
    env_file:
      - ./front/.env
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - carmeet-net

  db:
    image: mysql:8
    container_name: carmeet_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootsecret
      MYSQL_DATABASE: carmeet
      MYSQL_USER: carmeet_user
      MYSQL_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - carmeet-net

volumes:
  mysql_data:

networks:
  carmeet-net:
    driver: bridge
