const { Event } = require("../models");

async function seedEvents(users) {
  await Event.bulkCreate([
    {
      id_user: users[0].id_user,
      name: "Festival du Tuning Extrême",
      event_type: "tuning",
      description:
        "Venez admirer les voitures les plus modifiées de France. Ambiance musicale, animations et concours de sonorisation au programme. Une journée pour les passionnés et les curieux.",
      longitude: 2.4432,
      latitude: 48.7746,
      address: "5 rue des Mécanos",
      city: "Créteil",
      category: "Sport",
      event_date: "2025-06-20",
      event_time: "13:00:00",
      price: 25.0,
      available_seats: 100,
      is_featured: true,
    },
    {
      id_user: users[1].id_user,
      name: "Salon de l’Auto Ancienne",
      event_type: "exposition",
      description:
        "Découvrez une collection unique de voitures anciennes restaurées avec soin. Des modèles rares seront exposés avec des présentations de collectionneurs passionnés. Une belle sortie en famille.",
      longitude: 4.8357,
      latitude: 45.764,
      address: "12 place des moteurs",
      city: "Lyon",
      category: "Exposition",
      event_date: "2025-09-10",
      event_time: "09:00:00",
      price: 10.0,
      available_seats: 80,
      is_featured: false,
    },
    {
      id_user: users[0].id_user,
      name: "Journée Drift & Performance",
      event_type: "tuning",
      description:
        "Assistez à des démonstrations de drift par des pilotes professionnels. Ateliers techniques, stands de pièces auto et simulateurs seront disponibles. Sensations fortes garanties.",
      longitude: 1.4835,
      latitude: 43.5602,
      address: "Circuit de la Vitesse",
      city: "Toulouse",
      category: "Sport",
      event_date: "2025-07-05",
      event_time: "15:00:00",
      price: 30.0,
      available_seats: 70,
      is_featured: true,
    },
    {
      id_user: users[1].id_user,
      name: "Expo Supercars Françaises",
      event_type: "exposition",
      description:
        "Une exposition dédiée aux supercars produites en France. Bugatti, Alpine et d’autres marques seront mises en valeur. Venez admirer des véhicules d’exception dans un cadre prestigieux.",
      longitude: 2.1204,
      latitude: 48.8049,
      address: "Parc Expo Auto",
      city: "Versailles",
      category: "Exposition",
      event_date: "2025-10-12",
      event_time: "11:00:00",
      price: 20.0,
      available_seats: 60,
      is_featured: false,
    },
    {
      id_user: users[0].id_user,
      name: "Tuning Show de Bordeaux",
      event_type: "tuning",
      description:
        "Un grand rassemblement de tuning au cœur de Bordeaux. Concours de carrosseries custom, shows nocturnes et DJ sets. L’événement à ne pas manquer cet été.",
      longitude: -0.5792,
      latitude: 44.8378,
      address: "Zone Auto Bassin",
      city: "Bordeaux",
      category: "Sport",
      event_date: "2025-08-08",
      event_time: "17:00:00",
      price: 18.0,
      available_seats: 90,
      is_featured: true,
    },
    {
      id_user: users[1].id_user,
      name: "Rétrospective Auto 60-70",
      event_type: "exposition",
      description:
        "Un retour dans les années 60 et 70 à travers l’automobile. Ambiance rétro, véhicules emblématiques et accessoires d’époque. Animation musicale assurée par des groupes vintage.",
      longitude: 1.8739,
      latitude: 47.9025,
      address: "Parc Vintage Auto",
      city: "Orléans",
      category: "Exposition",
      event_date: "2025-09-22",
      event_time: "14:00:00",
      price: 12.0,
      available_seats: 40,
      is_featured: false,
    },
    {
      id_user: users[0].id_user,
      name: "Rassemblement Sport Mécanique",
      event_type: "tuning",
      description:
        "Courses, démonstrations et essais de véhicules sportifs. Espace enfants, foodtrucks et stands partenaires seront présents. Une expérience complète pour toute la famille.",
      longitude: 6.6336,
      latitude: 43.12,
      address: "Circuit du Var",
      city: "Draguignan",
      category: "Sport",
      event_date: "2025-07-30",
      event_time: "10:00:00",
      price: 22.0,
      available_seats: 75,
      is_featured: true,
    },
    {
      id_user: users[1].id_user,
      name: "Exposition Rallye Légendaire",
      event_type: "exposition",
      description:
        "Replongez dans l’univers du rallye avec les voitures de légende. Interviews de pilotes, projections vidéo et zone immersive. Idéal pour les amateurs d’adrénaline.",
      longitude: 3.0829,
      latitude: 45.7772,
      address: "Hall Rallye Expo",
      city: "Clermont-Ferrand",
      category: "Exposition",
      event_date: "2025-11-05",
      event_time: "13:30:00",
      price: 14.0,
      available_seats: 50,
      is_featured: false,
    },
    {
      id_user: users[0].id_user,
      name: "Tuning Night Strasbourg",
      event_type: "tuning",
      description:
        "Une nuit entière dédiée au tuning, avec des défilés, des sons puissants et une ambiance unique. Éclairages LED, concours de peinture et food court. De quoi passer une soirée mémorable.",
      longitude: 7.7521,
      latitude: 48.5734,
      address: "Esplanade Auto Show",
      city: "Strasbourg",
      category: "Sport",
      event_date: "2025-08-28",
      event_time: "19:00:00",
      price: 28.0,
      available_seats: 120,
      is_featured: true,
    },
    {
      id_user: users[1].id_user,
      name: "Salon de la Miniature Auto",
      event_type: "exposition",
      description:
        "Découvrez des maquettes et miniatures de véhicules historiques et modernes. Un événement pour les collectionneurs et les enfants. Vente et échanges possibles sur place.",
      longitude: 4.0473,
      latitude: 49.2583,
      address: "Salle Modélisme Auto",
      city: "Reims",
      category: "Exposition",
      event_date: "2025-10-01",
      event_time: "09:30:00",
      price: 8.0,
      available_seats: 60,
      is_featured: false,
    },
    {
      id_user: users[0].id_user,
      name: "Tuning Urbain Lille",
      event_type: "tuning",
      description:
        "Rencontre urbaine des passionnés de tuning. Performances de moteurs, lumières et sonorisation dans un cadre citadin. Animations DJ et stands de restauration rapide.",
      longitude: 3.0573,
      latitude: 50.6292,
      address: "Zone Custom Center",
      city: "Lille",
      category: "Sport",
      event_date: "2025-08-20",
      event_time: "16:00:00",
      price: 24.0,
      available_seats: 85,
      is_featured: true,
    },
    {
      id_user: users[1].id_user,
      name: "Voitures de Collection sur la Côte",
      event_type: "exposition",
      description:
        "Sur les bords de la Méditerranée, admirez une sélection de voitures de collection. Cadre idyllique, ambiance conviviale et exposition en plein air. Idéal pour les photographes et passionnés.",
      longitude: 7.265,
      latitude: 43.7102,
      address: "Promenade Auto d’Époque",
      city: "Nice",
      category: "Exposition",
      event_date: "2025-09-14",
      event_time: "10:30:00",
      price: 16.0,
      available_seats: 70,
      is_featured: false,
    },
  ]);

  console.log("12 événements insérés avec succès.");
}

module.exports = seedEvents;
