# Étape de build
FROM node:18

# Crée le répertoire de travail
WORKDIR /app

# Copie les fichiers nécessaires
COPY package*.json ./

# Installe les dépendances
RUN npm install

# Copie le reste du projet
COPY . .

# Expose le port de l’API
EXPOSE 3001

# Démarre le serveur
CMD ["node", "index.js"]