name: Déploiement automatique sur le VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Déploiement complet sur le VPS
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Connexion SSH et déploiement automatique
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Aller dans le dossier du projet"
            cd /srv/carmeet

            echo "Pull du dernier code"
            git pull origin main

            echo "Rebuild des conteneurs"
            docker compose down
            docker compose up -d --build

            echo "Déploiement terminé"
